const express = require('express');
const router = express.Router();
const userscontroller = require('../controllers/usercontroller');
const budgetcontroller = require('../controllers/budgetcontroller');
const expensecontroller = require('../controllers/expensecontroller');
const remindercontroller = require('../controllers/remindercontroller');
router.post('/addusers',userscontroller.adduser);
router.post('/loginuser',userscontroller.login);
router.post('/getid',userscontroller.getuserid);
router.post('/addbudget',budgetcontroller.addbudget);
router.post('/getuserbudget',budgetcontroller.getuserbudget);
router.post('/updateamount',budgetcontroller.update_amount);
router.post('/deletebudget',budgetcontroller.delete_budget);
router.post('/checkbudget',budgetcontroller.checkBudget);
router.post('/addexpense',expensecontroller.addexpense);
router.post('/getuserexpense',expensecontroller.getuserexpense);
router.post('/updateexpense',expensecontroller.update_amount);
router.post('/deleteexpense',expensecontroller.delete_expense);
router.post('/addreminder',remindercontroller.addreminder);
router.post('/updatedescription',remindercontroller.update_description);
router.post('/updatedate',remindercontroller.update_date);
router.post('/updatetime',remindercontroller.update_time);
router.post('/deletereminder',remindercontroller.delete_reminder);
router.post('/getuserreminder',remindercontroller.getuserreminder);
router.post('/checkdateandtime',remindercontroller.checkdateandtime);
module.exports = router;